graph TB
DataMesh[Data Mesh] --> DataAsProduct(Data as Product)

subgraph DataAsProduct
    DP1[Define and Design Data Products]
    DP2[Build and Maintain Data Products]
    DP3[Consider End-users Needs]
end