graph TB
DataMesh[Data Mesh] --> StandardizedDataExchange(Standardized Data Exchange and Governance)

subgraph StandardizedDataExchange
    SDE1[Data Exchange Formats]
    SDE2[APIs]
    SDE3[Metadata]
end